<a href="https://colab.research.google.com/github/Ramisettyjoshitha/numpy_practice/blob/main/%2003_numpy_reshaping_axis.ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Create an array containing numbers 1 to 12. Reshape it into a 3 × 4 array. Find its shape, ndim, and size.

In [8]:
a=np.arange(1,13)
b=a.reshape(3,4)
print(b)
print(b.shape)
print(b.size)
print(b.ndim)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
12
2


Create an array containing numbers 1 to 24. Reshape it using (4, -1). Predict the final shape before running it.

In [11]:
w=np.arange(1,25)
v=w.reshape(4,-1)
print(v.shape)
print(v)

(4, 6)
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


Create this array:
[[1, 2, 3],
 [4, 5, 6]]

Predict the output of reshaping it to (3, 2), then predict the output of transposing it. Explain why the results differ.

In [14]:
i=np.array([[1, 2, 3],
 [4, 5, 6]])
n=i.reshape(3,2)
print(n)

print(n.T)

[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


Convert a 3 × 4 array into a 1D array using both flatten() and ravel(). State the main difference between them.

In [15]:
l=np.arange(1,13).reshape(3,4)
o=l.flatten()
k=o.ravel()
print(o)
print(k)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


A 1D array has shape (5,). Convert it first to shape (1, 5) and then separately to shape (5, 1).

In [18]:
a = np.array([1, 2, 3, 4, 5])
row=a[np.newaxis,:]
col=a[:,np.newaxis]
print(row.shape)
print(col.shape)

(1, 5)
(5, 1)


n array has shape (1, 3, 1). What will its shape become after using squeeze()

In [20]:
a = np.array([[[1], [2], [3]]])
b=a.squeeze()
print(b.shape)

(3,)


For this array:
[[1, 2, 3],
 [4, 5, 6]]

Find the sum using axis=0 and axis=1. Predict both outputs before running the code.

In [22]:
a=np.array([[1, 2, 3],
 [4, 5, 6]])
b=a.sum(axis=0)
c=a.sum(axis=1)
print(b)
print(c)

[5 7 9]
[ 6 15]


For this array:
[[10, 20],
 [30, 40],
 [50, 60]]

Find the mean using axis=0 and axis=1

In [23]:
a=np.array([[10, 20],
 [30, 40],
 [50, 60]])
b=a.mean(axis=0)
c=a.mean(axis=1)
print(b)
print(c)

[30. 40.]
[15. 35. 55.]
