<a href="https://colab.research.google.com/github/Ramisettyjoshitha/numpy_practice/blob/main/01_numpy_array_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


Question 1: Create a 1D array containing 10, 20, 30, 40, 50. Find its ndim, shape, size, and dtype.

In [1]:
import numpy as np

In [2]:
array=np.array([10,20,30,40,50])

In [5]:
print(array.ndim)
print(array.shape)
print(array.size)
print(array.dtype)

1
(5,)
5
int64


Question 2 : Create this 2D array:

[[10, 20, 30],
 [40, 50, 60]]

Predict its ndim, shape, and size before running it

In [4]:
a=np.array([[1,2,3],[4,5,6]])

In [6]:
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

2
(2, 3)
6
int64


Question 2 : Create a 3 × 4 array containing only zeros.

In [12]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])


Create a 2 × 5 array filled with the value 8.



In [13]:
np.full((2,5),8)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

Using arange(), create:

[5, 10, 15, 20, 25, 30]

In [19]:
z=np.arange(5,31,5)
print(z)

[ 5 10 15 20 25 30]


Using arange(), create all odd numbers from 1 to 19

In [20]:
z=np.arange(1,19,2)
print(z)

[ 1  3  5  7  9 11 13 15 17]


Using linspace(), create exactly 6 evenly spaced numbers from 0 to 10.

In [24]:
a=np.linspace(0,10,6)
print(a)

[ 0.  2.  4.  6.  8. 10.]
