<a href="https://colab.research.google.com/github/Ramisettyjoshitha/numpy_practice/blob/main/02_numpy_indexing_slicing..ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.array([
    [ 1,  2,  3,  4,  5],
    [ 6,  7,  8,  9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
])

Extract the value 14 using positive indexing.

In [ ]:
print(a[2][3])

14


Extract the value 22 using negative indexing.

In [ ]:
print(a[-1][-4])

22


Extract the center 3 × 3 array.

In [ ]:
print(a[1:4,1:4])

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


Extract alternate rows and alternate columns to get [[1,3,5],[11,13,15],[21,23,25]].


In [ ]:
print(a[0::2,0::2])

[[ 1  3  5]
 [11 13 15]
 [21 23 25]]


Extract the last two rows and last three columns.

In [11]:
print(a[-2:,:-3])

[[16 17]
 [21 22]]


Extract [[25,24,23],[20,19,18],[15,14,13]].

In [14]:
print(a[:-4:-1,:-4:-1])

[[25 24 23]
 [20 19 18]
 [15 14 13]]


Extract [[21,22,23],[11,12,13],[1,2,3]].

In [22]:
print(a[4::-2, :3])

[[21 22 23]
 [11 12 13]
 [ 1  2  3]]


Extract [[5,3,1],[15,13,11],[25,23,21]]

In [27]:
print(a[0::2,::-2])

[[ 5  3  1]
 [15 13 11]
 [25 23 21]]


Extract [[24,22],[14,12],[4,2]].

In [29]:
print(a[::-2,-2:-5:-2])

[[24 22]
 [14 12]
 [ 4  2]]
